source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/HuuLiang/HLPodRepo.git'
platform :ios, '8.0'

#use_frameworks!

inhibit_all_warnings!

target 'HLShellModule_Example' do
  pod 'HLShellModule', :path => '../'
end
