#use_frameworks!
use_modular_headers!


target 'HLToolKit-Swift_Example' do
  pod 'HLToolKit-Swift', :path => '../'

#  target 'HLToolKit-Swift_Tests' do
#    inherit! :search_paths
#
#
#  end
end

#pre_install do |installer|
#  Pod::PodTarget.send(:define_method, :static_framework?) { return true }
#end

