source 'https://cdn.cocoapods.org/'

use_modular_headers!

platform :ios, '11.0'

target 'HLSwiftKit_Example' do
  pod 'HLSwiftKit', :path => '../'

  target 'HLSwiftKit_Tests' do
    inherit! :search_paths

    
  end
end
